---
- name: create alias file
  template:
    src: bash_aliases.j2
    dest: '/home/{{ deployment_user }}/.bash_aliases'
    owner: '{{deployment_user}}'
    group: '{{deployment_user}}'
    mode: 0644

- name: check if exa_alias already added
  shell: grep -c 'alias ls="exa"' /home/{{ deployment_user }}/.bash_aliases || true
  register: exa_alias

- name: add exa alias
  lineinfile:
    path: '/home/{{ deployment_user }}/.bash_aliases'
    line: 'alias ls="exa"'
    insertbefore: EOF
  when: exa|default(false)|bool == true and not exa_alias|bool

- name: check if duf_alias already added
  shell: grep -c 'alias df="duf"' /home/{{ deployment_user }}/.bash_aliases || true
  register: duf_alias

- name: add duf alias
  lineinfile:
    path: '/home/{{ deployment_user }}/.bash_aliases'
    line: 'alias df="duf"'
    insertbefore: EOF
  when: duf|default(false)|bool == true and not exa_alias|bool