---
- name: Create Ansible user
  user:
    name: ansible
    comment: 'Ansible user'
    shell: /bin/bash

- name: Copy ssh keys for Ansible user
  copy:
    src: ~/.ssh
    dest: /home/ansible/
    owner: ansible
    group: ansible
    remote_src: true

- name: Allow sudo for ansible
  copy:
    content: 'ansible ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/ansible
    mode: 0600

- name: Create administrator user
  user:
    name: '{{ deployment_user }}'
    comment: 'admin user'
    shell: /bin/bash

- name: Copy ssh keys for administrator user
  copy:
    src: ~/.ssh
    dest: '/home/{{ deployment_user }}/'
    owner: '{{ deployment_user }}'
    group: '{{ deployment_user }}'
    remote_src: true

- name: Allow sudo for administrator
  copy:
    content: '{{ deployment_user }} ALL=(ALL) NOPASSWD: ALL'
    dest: '/etc/sudoers.d/{{ deployment_user }}'
    mode: 0600
