---
- name: Clone bash-git-prompt repo
  git:
    repo: 'https://github.com/magicmonty/bash-git-prompt.git'
    dest: '/usr/local/bin/bash-git-prompt'
    depth: 1
    update: yes

- name: Change owner
  file:
    dest: '/home/{{ deployment_user }}/.bash-git-prompt'
    owner: '{{ deployment_user }}'
    group: '{{ deployment_user }}'
    recurse: yes

- name: Add bash-git-prompt to .bashrc
  blockinfile:
    dest: '/home/{{ deployment_user }}/.bashrc'
    block: |
      if [ -f "/usr/local/bin/bash-git-prompt/gitprompt.sh" ]; then
          GIT_PROMPT_ONLY_IN_REPO=1
          source /usr/local/bin/bash-git-prompt/gitprompt.sh
      fi
    marker: '# {mark} ANSIBLE MANAGED BLOCK - bash-git-prompt'
    insertbefore: EOF
    create: yes
